### ISSUE TITLE
A "Home" or "About" page should exist on the BSRC website

### ISSUE THREAD

**Issue by remomueller** [sleepepi/bsrc#1]
From @mrueschman 

> I started sketching an “About” section. I took a similar tact to Echo Core, i.e. 1 paragraph about the group and 1 paragraph about the Director.
> 
> > The Boston Sleep Reading Center (BSRC) excels in the assessment of many types of physiological data in support of large-scale, academic research projects. For more than 20 years we have worked with major NIH studies and industry partners to facilitate the acquisition and analysis of polysomnography, actigraphy, oximetry, pharyngometry, ambulatory blood pressure, and more. The BSRC maintains high standards of reliability and rigor in its generation of research results from the review and scoring of physiological data.
> > 
> > Dr. Susan Redline serves as Director of the Boston Sleep Reading Center. Upon establishing the BSRC in 1994, she supported data collection for the Sleep Heart Health Study, the first large-scale, multi-center sleep cohort study. In her career, Dr. Redline has published more than 200 scientific papers, chapters, reviews, and editorials on the science of sleep. She directs the Program in Sleep and Cardiovascular Medicine within the Division of Sleep and Circadian Disorders at Brigham and Women's Hospital.

**Comment by mrueschman** [comment]
The "Welcome!" seems superfluous, let's get rid of it. Plus it eliminates an exclamation mark!

![image](https://cloud.githubusercontent.com/assets/707167/6419245/a0372da4-be89-11e4-9153-164a766e7a44.png)

@remomueller @krand7
