### ISSUE TITLE
A 'Services' page should exist on the BSRC site

### ISSUE THREAD

**Issue by krand7** [sleepepi/bsrc#3]

**Comment by mrueschman** [comment]
Maybe we can have an introductory paragraph here and then break this page down into subsections, such as:

- Polysomnography
- Actigraphy
- Data Management
- Informatics

Introductory paragraph:

The BSRC helps others make meaning of complex physiological data in research settings. Over the past 20 years we have scored and assessed data from more than 50,000 individual research subjects across numerous studies. The BSRC offers services that cover the entire life cycle of research projects, including protocol development, site staff certification, data management, and statistical analyses. 

I'll add more later.
