### ISSUE TITLE
Use cooler webfont family

### ISSUE THREAD

**Issue by mrueschman** [sleepepi/bsrc#7]
Looks gross on Windows. Let's jazz this site up! :tada:

**Comment by mrueschman** [comment]
Maybe we could try one of these? 

http://www.google.com/fonts#UsePlace:use/Collection:Lato
http://www.google.com/fonts/specimen/Actor
http://www.fontsquirrel.com/fonts/tikal-sans

**Comment by mcailler** [comment]
http://www.google.com/fonts/specimen/Noto+Sans

**Comment by remomueller** [comment]
It should actually look identical on Windows, or close, perhaps the webfont isn't being loaded properly?

**Comment by krand7** [comment]
It's currently pulling from a CDN because I'm not in love with the font -- once it's finalized we can download to otf file

**Comment by remomueller** [comment]
Looks like this was partially addressed with commit fd302ec7523536e0e415b11ba0cf14d850475858, but `.woff` files are still missing for OpenSans.
